version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  seed:
    build: ./server
    container_name: cyberaegiz_seed
    entrypoint: ["node", "seed.js"]
    environment:
      - MONGO_URI=mongodb://mongo:27017/cyberaegiz
    depends_on:
      - mongodb

  server:
    build: ./server
    container_name: cyberaegiz_server
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cyberaegiz
    depends_on:
      - mongodb
      - seed
    command: ["node", "server.js"]

  client:
    build: ./client
    container_name: cyberaegiz_client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data:
